# Java projeleri için pre-commit yapılandırması (EKSTRA İNDİRME YOK)
# Kurulum: `pre-commit install`
# Manuel çalıştırma: `pre-commit run --all-files`

# pip install pre-commit
# pre-commit install
# pre-commit run --all-files


repos:


  # === JAVA KONTROLLERİ ===
  - repo: local
    hooks:
      - id: check-java-files
        name: Java Dosya Kontrolü
        entry: "bash -c \"find . -name '*.java' -print\""
        language: system
        pass_filenames: false
        types: [java]

      - id: check-maven-pom
        name: Maven POM XML doğrulama
        entry: "bash -c \"if [ -f pom.xml ]; then xmllint --noout pom.xml; else echo 'No pom.xml found'; fi\""
        language: system
        types: [xml]
        files: 'pom.xml'

      - id: run-java-tests
        name: JUnit Testleri Çalıştır
        entry: "bash -c \"if [ -f pom.xml ]; then mvn test; else echo 'No pom.xml, skipping tests'; fi\""
        language: system
        types: [java]
        
      - id: prevent-system-out
        name: System.out.println Kullanımını Engelle
        entry: "bash -c \"grep -rnw '.' -e 'System.out.println' && echo '❌ System.out.println kullanılmamalıdır!' && exit 1 || exit 0\""
        language: system
        pass_filenames: false
        types: [java]
