name: 'spring-boot-erp'
services:
  accounting-db:
    image: postgres:17-alpine
    container_name: accounting-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting-db
    ports:
      - "15432:5432"
    volumes:
      - accounting-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
     resources:
      limits:
       memory: 500m
volumes:
  accounting-db-data: